apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ngey
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-ngey@sha256:62b2a6abeb0e64e61f1eb659661bbe24ee7cdecf1ee2afd98873e5be531392bf
        name: my-nodejs
        resources: {}
status: {}
